# Generated by Django 2.0 on 2018-03-27 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0012_auto_20170927_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='byline_photo',
            field=models.ForeignKey(
                blank=True,
                help_text='photo used for byline credit.',
                limit_choices_to={'category': 4},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='person',
                to='photo.ImageFile'
            ),
        ),
    ]
