# Generated by Django 2.1 on 2018-08-13 14:16

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0015_auto_20180421_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='created',
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name='created'
            ),
        ),
        migrations.AddField(
            model_name='contributor',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name='modified'
            ),
        ),
    ]
