# Generated by Django 2.0 on 2018-05-03 19:47

from django.db import migrations, models


def update_frontpagestories(apps, schema_editor):

    Story = apps.get_model("stories", "Story")
    FrontpageStory = apps.get_model("frontpage", "FrontpageStory")

    # delete unneeded
    FrontpageStory.objects.filter(storymodule=None).delete()
    FrontpageStory.objects.exclude(story__publication_status=10, ).delete()

    # set columns and rows
    columns_translate = {1: 2, 2: 2, 3: 2, 4: 3, 5: 3, 6: 4, 7: 4, 8: 4}
    rows_translate = {1: 2, 2: 3, 3: 4}
    FrontpageStory.objects.update(columns=6, rows=6)
    for k, v in columns_translate.items():
        FrontpageStory.objects.filter(storymodule__columns=k).update(columns=v)
    for k, v in rows_translate.items():
        FrontpageStory.objects.filter(storymodule__height=k).update(rows=v)

    # update order
    FrontpageStory.objects.update(
        order=models.Subquery(
            Story.objects.filter(frontpagestory=models.OuterRef('id')
                                 ).annotate(
                                     timestamp=models.functions.
                                     Extract('publication_date', 'epoch') /
                                     3600
                                 ).values('timestamp')[:1]
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0005_auto_20150430_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpagestory',
            name='columns',
            field=models.PositiveSmallIntegerField(
                choices=[(2, '2'), (3, '3'), (4, '4'), (6, '6')],
                default=3,
                help_text='base width',
                verbose_name='columns'
            ),
        ),
        migrations.AddField(
            model_name='frontpagestory',
            name='order',
            field=models.FloatField(
                default=0, editable=False, verbose_name='order'
            ),
        ),
        migrations.AddField(
            model_name='frontpagestory',
            name='priority',
            field=models.FloatField(
                default=0,
                help_text='Modify ordering.',
                verbose_name='priority'
            ),
        ),
        migrations.AddField(
            model_name='frontpagestory',
            name='rows',
            field=models.PositiveIntegerField(
                choices=[(2, '2'), (3, '3'), (4, '4'), (6, '6')],
                default=2,
                help_text='base height',
                verbose_name='rows'
            ),
        ),
        migrations.RunPython(
            code=update_frontpagestories,
            reverse_code=migrations.RunPython.noop,
        )
    ]
