# Generated by Django 2.0 on 2018-05-03 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0006_prepare_frontpagemodule_removal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticmodule',
            name='frontpage',
        ),
        migrations.RemoveField(
            model_name='storymodule',
            name='frontpage',
        ),
        migrations.RemoveField(
            model_name='storymodule',
            name='frontpage_story',
        ),
        migrations.RemoveField(
            model_name='frontpagestory',
            name='placements',
        ),
        migrations.DeleteModel(
            name='Frontpage',
        ),
        migrations.DeleteModel(
            name='StaticModule',
        ),
        migrations.DeleteModel(
            name='StoryModule',
        ),
    ]
