# Generated by Django 2.0 on 2018-05-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0007_auto_20180503_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontpagestory',
            name='order',
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name='order'
            ),
        ),
    ]
