# Generated by Django 2.0 on 2018-05-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0008_auto_20180504_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpagestory',
            name='published',
            field=models.BooleanField(default=True, help_text='published', verbose_name='published'),
        ),
    ]
