# Generated by Django 2.0 on 2018-05-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0009_frontpagestory_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontpagestory',
            name='rows',
            field=models.PositiveIntegerField(
                choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (6, '6'),
                         (8, '8')],
                default=2,
                help_text='base height',
                verbose_name='rows'
            ),
        ),
    ]
