# Generated by Django 2.1 on 2018-08-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0010_auto_20180529_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontpagestory',
            name='rows',
            field=models.PositiveIntegerField(
                choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'),
                         (6, '6')],
                default=2,
                help_text='base height',
                verbose_name='rows'
            ),
        ),
    ]
