# Generated by Django 2.0 on 2017-12-07 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_data_load_publication_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printissue',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pdfs', to='issues.Issue'),
        ),
    ]
