# Generated by Django 2.1.5 on 2019-04-08 13:23

import apps.issues.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0012_auto_20171207_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='publication_date',
            field=models.DateField(default=apps.issues.models.today),
        ),
    ]
