// http://gorangajic.github.io/react-icons/md.html
//
export Add from 'react-icons/lib/md/add-circle'
export Aside from 'react-icons/lib/md/subject'
export BulletList from 'react-icons/lib/md/format-list-bulleted'
export Camera from 'react-icons/lib/md/photo-camera'
export Clear from 'react-icons/lib/md/clear'
export Close from 'react-icons/lib/md/close'
export Comment from 'react-icons/lib/md/announcement'
export Crop from 'react-icons/lib/md/crop'
export Delete from 'react-icons/lib/md/delete'
export Edit from 'react-icons/lib/md/edit'
export Email from 'react-icons/lib/md/email'
export Fallback from 'react-icons/lib/fa/exclamation-triangle'
export GridView from 'react-icons/lib/md/view-module'
export Heading from 'react-icons/lib/fa/header'
export Laptop from 'react-icons/lib/md/laptop-chromebook'
export ListView from 'react-icons/lib/md/view-list'
export Newspaper from 'react-icons/lib/md/import-contacts'
export Pdf from 'react-icons/lib/md/picture-as-pdf'
export Person from 'react-icons/lib/md/person'
export Phone from 'react-icons/lib/md/phone'
export Question from 'react-icons/lib/fa/question-circle'
export Quote from 'react-icons/lib/md/format-quote'
export Tune from 'react-icons/lib/md/tune'
