# Generated by Django 2.0 on 2018-04-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0024_auto_20180421_1957'),
        ('stories', '0002_data_load_sections_and_storytypes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storyimage',
            unique_together={('parent_story', 'imagefile')},
        ),
    ]
