# Generated by Django 2.0 on 2018-05-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20180429_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='url',
            field=models.URLField(blank=True, default='', editable=False),
        ),
    ]
