# Generated by Django 2.0 on 2018-06-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_auto_20180529_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storyimage',
            options={
                'ordering': ['-top', 'index'], 'verbose_name': 'Image',
                'verbose_name_plural': 'Images'
            },
        ),
        migrations.AddField(
            model_name='aside',
            name='ordering',
            field=models.SmallIntegerField(
                blank=True,
                default=0,
                help_text='Internal order within placement',
                null=True,
                verbose_name='ordering'
            ),
        ),
        migrations.AddField(
            model_name='aside',
            name='placement',
            field=models.CharField(
                blank='true',
                default='auto',
                help_text='Placement of this element',
                max_length=100,
                verbose_name='placement'
            ),
        ),
        migrations.AddField(
            model_name='inlinehtml',
            name='ordering',
            field=models.SmallIntegerField(
                blank=True,
                default=0,
                help_text='Internal order within placement',
                null=True,
                verbose_name='ordering'
            ),
        ),
        migrations.AddField(
            model_name='inlinehtml',
            name='placement',
            field=models.CharField(
                blank='true',
                default='auto',
                help_text='Placement of this element',
                max_length=100,
                verbose_name='placement'
            ),
        ),
        migrations.AddField(
            model_name='pullquote',
            name='ordering',
            field=models.SmallIntegerField(
                blank=True,
                default=0,
                help_text='Internal order within placement',
                null=True,
                verbose_name='ordering'
            ),
        ),
        migrations.AddField(
            model_name='pullquote',
            name='placement',
            field=models.CharField(
                blank='true',
                default='auto',
                help_text='Placement of this element',
                max_length=100,
                verbose_name='placement'
            ),
        ),
        migrations.AddField(
            model_name='storyimage',
            name='ordering',
            field=models.SmallIntegerField(
                blank=True,
                default=0,
                help_text='Internal order within placement',
                null=True,
                verbose_name='ordering'
            ),
        ),
        migrations.AddField(
            model_name='storyimage',
            name='placement',
            field=models.CharField(
                blank='true',
                default='auto',
                help_text='Placement of this element',
                max_length=100,
                verbose_name='placement'
            ),
        ),
        migrations.AddField(
            model_name='storyvideo',
            name='ordering',
            field=models.SmallIntegerField(
                blank=True,
                default=0,
                help_text='Internal order within placement',
                null=True,
                verbose_name='ordering'
            ),
        ),
        migrations.AddField(
            model_name='storyvideo',
            name='placement',
            field=models.CharField(
                blank='true',
                default='auto',
                help_text='Placement of this element',
                max_length=100,
                verbose_name='placement'
            ),
        ),
    ]
