# Generated by Django 2.0 on 2018-06-17 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_storychild_placement_and_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storyimage',
            options={'ordering': ['-ordering'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.RemoveField(
            model_name='aside',
            name='top',
        ),
        migrations.RemoveField(
            model_name='inlinehtml',
            name='top',
        ),
        migrations.RemoveField(
            model_name='pullquote',
            name='top',
        ),
        migrations.RemoveField(
            model_name='storyimage',
            name='top',
        ),
        migrations.RemoveField(
            model_name='storyvideo',
            name='top',
        ),
    ]
