# Generated by Django 2.0 on 2018-07-06 13:32

from django.db import migrations, models


def all_auto_ratio(apps, schema_editor):
    for model_name in 'StoryImage', 'StoryVideo':
        Model = apps.get_model('stories', model_name)
        Model.objects.filter(aspect_ratio=100).update(aspect_ratio=0)
        Model.objects.filter(aspect_ratio=0.667).update(aspect_ratio=0.6667)
        Model.objects.filter(aspect_ratio=1.333).update(aspect_ratio=1.3333)


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_remove_story_bylines_html'),
    ]

    operations = [
        migrations.RunPython(
            code=all_auto_ratio,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='storyimage',
            name='aspect_ratio',
            field=models.FloatField(
                choices=[
                    (0.0, 'auto'),
                    (0.4, '5:2 landscape'),
                    (0.5, '2:1 landscape'),
                    (0.5625, '16:9 landscape (youtube)'),
                    (0.6667, '3:2 landscape'),
                    (0.75, '4:3 landscape'),
                    (1.0, '1:1 square'),
                    (1.3333, '3:4 portrait'),
                    (1.5, '2:3 portrait'),
                    (2.0, '1:2 portrait'),
                ],
                default=0.0,
                help_text='height / width',
                verbose_name='aspect ratio'
            ),
        ),
        migrations.AlterField(
            model_name='storyvideo',
            name='aspect_ratio',
            field=models.FloatField(
                choices=[
                    (0.0, 'auto'),
                    (0.4, '5:2 landscape'),
                    (0.5, '2:1 landscape'),
                    (0.5625, '16:9 landscape (youtube)'),
                    (0.6667, '3:2 landscape'),
                    (0.75, '4:3 landscape'),
                    (1.0, '1:1 square'),
                    (1.3333, '3:4 portrait'),
                    (1.5, '2:3 portrait'),
                    (2.0, '1:2 portrait'),
                ],
                default=0.0,
                help_text='height / width',
                verbose_name='aspect ratio'
            ),
        ),
    ]
