# Generated by Django 2.0 on 2018-07-07 16:56

from django.db import migrations, models


def populate_link_names(apps, schema_editor):
    InlineLink = apps.get_model('stories', 'InlineLink')
    InlineLink.objects.update(
        link_name=models.functions.Cast('number', models.CharField())
    )


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_story_media_aspect_ratios'),
    ]

    operations = [
        migrations.AddField(
            model_name='inlinelink',
            name='link_name',
            field=models.CharField(
                blank=True, default='', help_text='link label', max_length=256
            ),
        ),
        migrations.RunPython(
            code=populate_link_names, reverse_code=migrations.RunPython.noop
        ),
    ]
