# Generated by Django 2.0 on 2018-08-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0011_story_related_stories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='related_stories',
            field=models.ManyToManyField(
                blank=True,
                related_name='_story_related_stories_+',
                to='stories.Story',
                verbose_name='related stories'
            ),
        ),
    ]
