# Generated by Django 2.1.2 on 2018-11-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_auto_20180801_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aside',
            name='placement',
            field=models.CharField(
                blank='true',
                default='head',
                help_text='Placement of this element',
                max_length=100,
                verbose_name='placement'
            ),
        ),
        migrations.AlterField(
            model_name='inlinehtml',
            name='placement',
            field=models.CharField(
                blank='true',
                default='head',
                help_text='Placement of this element',
                max_length=100,
                verbose_name='placement'
            ),
        ),
        migrations.AlterField(
            model_name='pullquote',
            name='placement',
            field=models.CharField(
                blank='true',
                default='head',
                help_text='Placement of this element',
                max_length=100,
                verbose_name='placement'
            ),
        ),
        migrations.AlterField(
            model_name='storyimage',
            name='placement',
            field=models.CharField(
                blank='true',
                default='head',
                help_text='Placement of this element',
                max_length=100,
                verbose_name='placement'
            ),
        ),
        migrations.AlterField(
            model_name='storyvideo',
            name='placement',
            field=models.CharField(
                blank='true',
                default='head',
                help_text='Placement of this element',
                max_length=100,
                verbose_name='placement'
            ),
        ),
    ]
