# Generated by Django 2.1.5 on 2019-02-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0014_auto_20190219_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='strossle_enabled',
            field=models.BooleanField(default=False, help_text='Enable Strossle'),
        ),
    ]
