# Generated by Django 2.1.5 on 2019-02-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0015_story_strossle_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='strossle_enabled',
            field=models.BooleanField(
                default=True, help_text='Enable Strossle'
            ),
        ),
    ]
