# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0021_data_generate_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='publication_status',
            field=models.IntegerField(choices=[(0, 'Draft'), (5, 'Ready to edit'), (9, 'Ready to publish on website'), (10, 'Published on website'), (11, 'Published, but hidden from search engines'), (15, 'Will not be published'), (100, 'Used as template for new articles'), (500, 'Technical error')], default=0, help_text='publication status.', verbose_name='status'),
        ),
    ]
