# Generated by Django 1.11 on 2017-08-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0022_auto_20161228_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='publication_status',
            field=models.IntegerField(choices=[(0, 'Draft'), (5, 'Ready to edit'), (6, 'Ready for newsdesk'), (9, 'Ready to publish on website'), (10, 'Published on website'), (11, 'Published, but hidden from search engines'), (15, 'Will not be published'), (100, 'Used as template for new articles'), (500, 'Technical error')], default=0, help_text='publication status.', verbose_name='status'),
        ),
    ]
