# Generated by Django 1.11 on 2017-08-18 14:01

from django.db import migrations, models


def populate_working_title(apps, schema_editor):
    Story = apps.get_model('stories', 'Story')
    stories = Story.objects.using(schema_editor.connection.alias).all()
    stories.update(working_title=models.F('title'))


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0024_auto_20170815_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='working_title',
            field=models.CharField(
                blank=True,
                help_text='Working title',
                max_length=1000,
                verbose_name='Working title'
            ),
        ),
        migrations.RunPython(
            code=populate_working_title,
            reverse_code=migrations.RunPython.noop,
        )
    ]
