# Generated by Django 1.11 on 2017-09-27 17:04

import apps.stories.models.sections
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0026_auto_20170822_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storytype',
            name='template',
        ),
        migrations.AlterField(
            model_name='story',
            name='issue',
            field=models.ForeignKey(
                blank=True,
                help_text='which issue this story was printed in.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='issues.PrintIssue',
                verbose_name='issue'
            ),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_type',
            field=models.ForeignKey(
                default=apps.stories.models.sections.default_story_type,
                help_text='the type of story.',
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to='stories.StoryType',
                verbose_name='article type'
            ),
        ),
        migrations.AlterField(
            model_name='storytype',
            name='section',
            field=models.ForeignKey(
                default=apps.stories.models.sections.default_section,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to='stories.Section'
            ),
        ),
    ]
