# Generated by Django 1.11 on 2017-09-28 18:41

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0027_auto_20170927_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storytype',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, default='storytype-slug', editable=False, overwrite=True, populate_from=['name'], verbose_name='slug'),
        ),
    ]
