# Generated by Django 1.11 on 2017-10-18 16:03

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0029_auto_20171016_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
    ]
