# Generated by Django 1.11 on 2017-11-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0030_auto_20171018_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='comment_field',
            field=models.CharField(choices=[('disqus', 'disqus'), ('facebook', 'facebook'), ('', 'off')], default='disqus', help_text='Enable comment field', max_length=16, verbose_name='Comment Field'),
        ),
    ]
