# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-22 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0031_story_comment_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='comment_field',
            field=models.CharField(choices=[('facebook', 'facebook'), ('disqus', 'disqus'), ('off', 'off')], default='facebook', help_text='Enable comment field', max_length=16, verbose_name='Comment Field'),
        ),
    ]
