# Generated by Django 2.0 on 2018-04-12 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0033_auto_20180412_1610'),
    ]

    operations = [
        migrations.RunSQL('DROP TABLE stories_storyelement'),
        # migrations.DeleteModel(name='StoryElement', ),
        migrations.AlterField(
            model_name='aside',
            name='parent_story',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='asides',
                to='stories.Story'
            ),
        ),
        migrations.AlterField(
            model_name='inlinehtml',
            name='parent_story',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='inline_html_blocks',
                to='stories.Story'
            ),
        ),
        migrations.AlterField(
            model_name='pullquote',
            name='parent_story',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='pullquotes',
                to='stories.Story'
            ),
        ),
        migrations.AlterField(
            model_name='storyimage',
            name='parent_story',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='images',
                to='stories.Story'
            ),
        ),
        migrations.AlterField(
            model_name='storyvideo',
            name='parent_story',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='videos',
                to='stories.Story'
            ),
        ),
    ]
