// http://react-icons.github.io/react-icons/md.html

export {
  MdAdd as Add,
  MdAnnouncement as Announce,
  MdArtTrack as ArtTrack,
  MdSubject as Aside,
  MdFormatListBulleted as BulletList,
  MdPhotoCamera as Camera,
  MdCameraRoll as CameraRoll,
  MdClear as Clear,
  MdClose as Close,
  MdComment as Comment,
  MdCrop as Crop,
  MdDelete as Delete,
  MdDescription as Description,
  MdDone as Done,
  MdFileDownload as Download,
  MdEdit as Edit,
  MdError as Error,
  MdRemoveRedEye as Eye,
  MdFileUpload as Upload,
  MdArrowForward as Forward,
  MdViewModule as GridView,
  MdInfo as Info,
  MdLaptopChromebook as Laptop,
  MdViewList as ListView,
  MdLink as Link,
  MdLoop as Loop,
  MdMenu as Menu,
  MdImportContacts as Newspaper,
  MdPictureAsPdf as Pdf,
  MdPerson as Person,
  MdFormatQuote as Quote,
  MdSearch as Search,
  MdSync as Sync,
  MdPhone as Phone,
  MdTextFields as TextFields,
  MdAccessTime as Time,
  MdTransform as Transform,
  MdTune as Tune,
} from 'react-icons/md'

export {
  FaHeading as Heading,
  FaExclamationTriangle as Fallback,
  FaMagic as Magic,
  FaQuestionCircle as Question,
} from 'react-icons/fa'
