# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 14:14
from __future__ import unicode_literals

import apps.photo.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_auto_20151025_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='_md5',
            field=models.CharField(editable=False, help_text='md5 hash of source file', max_length=32, null=True, verbose_name='md5'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='_mtime',
            field=models.PositiveIntegerField(editable=False, help_text='mtime timestamp of source file', null=True, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='_size',
            field=models.PositiveIntegerField(editable=False, help_text='size of file in bytes', null=True, verbose_name='file size'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='contributor',
            field=models.ForeignKey(blank=True, help_text='who made this', null=True, on_delete=django.db.models.deletion.CASCADE, to='contributors.Contributor', verbose_name='contributor'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='copyright_information',
            field=models.CharField(blank=True, help_text='extra information about license and attribution if needed.', max_length=1000, null=True, verbose_name='copyright information'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='crop_diameter',
            field=models.PositiveSmallIntegerField(default=100, help_text='area containing most relevant content. Area is considered a circle with center x,y and diameter d where x and y are the values "from_left" and "from_right" and d is a percentage of the shortest axis. This is used for close cropping of some images, for instance byline photos.', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='crop diameter'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='cropping_method',
            field=models.PositiveSmallIntegerField(choices=[(0, 'center'), (5, 'corner detection'), (10, 'multiple faces'), (15, 'single face'), (100, 'manual crop')], default=0, help_text='How this image has been cropped.', verbose_name='cropping method'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='from_left',
            field=models.PositiveSmallIntegerField(default=50, help_text='image crop horizontal. Between 0% and 100%.', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='from left'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='from_top',
            field=models.PositiveSmallIntegerField(default=50, help_text='image crop vertical. Between 0% and 100%.', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='from top'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='full_height',
            field=models.PositiveIntegerField(editable=False, help_text='full height in pixels', null=True, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='full_width',
            field=models.PositiveIntegerField(editable=False, help_text='full height in pixels', null=True, verbose_name='width'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='old_file_path',
            field=models.CharField(blank=True, help_text='previous path if the image has been moved.', max_length=1000, null=True, verbose_name='old file path'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='source_file',
            field=sorl.thumbnail.fields.ImageField(height_field='full_height', max_length=1024, upload_to=apps.photo.models.upload_image_to, verbose_name='source file', width_field='full_width'),
        ),
    ]
