# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_auto_20160906_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='cropping_method',
            field=models.PositiveSmallIntegerField(choices=[(0, 'center'), (1, 'pending'), (5, 'corner detection'), (10, 'multiple faces'), (15, 'single face'), (100, 'manual crop')], default=1, help_text='How this image has been cropped.', verbose_name='cropping method'),
        ),
    ]
