# Generated by Django 1.11 on 2017-04-20 20:17

from django.db import migrations

from utils.model_fields import BoxField, CropBox


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0008_auto_20170214_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='crop_box',
            field=BoxField(
                default=CropBox.basic,
                help_text='How this image has been cropped.',
                null=True,
                verbose_name='crop box'
            ),
        ),
    ]
