# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0010_data_imagefile_cropbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefile',
            name='crop_diameter',
        ),
        migrations.RemoveField(
            model_name='imagefile',
            name='from_left',
        ),
        migrations.RemoveField(
            model_name='imagefile',
            name='from_top',
        ),
    ]
