# Generated by Django 1.11 on 2017-05-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0011_auto_20170422_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='_imagehash',
            field=models.CharField(
                default='',
                editable=False,
                help_text='perceptual hash of image using dhash algorithm',
                max_length=16,
                verbose_name='image hash'),
        ),
    ]
