# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0012_imagefile__imagehash'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='description',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Description of image',
                max_length=1000,
                verbose_name='copyright information'),
        ),
    ]
