# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-02 09:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0016_postgresql_create_trigram_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Description of image', max_length=1000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='exif_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False, help_text='exif_data', verbose_name='exif_data'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='old_file_path',
            field=models.CharField(blank=True, editable=False, help_text='previous path if the image has been moved.', max_length=1000, null=True, verbose_name='old file path'),
        ),
    ]
