# Generated by Django 2.0 on 2017-12-07 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0017_auto_20171002_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='contributor',
            field=models.ForeignKey(blank=True, help_text='who made this', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contributors.Contributor', verbose_name='contributor'),
        ),
    ]
