# Generated by Django 2.0 on 2018-04-12 14:10

import django.core.serializers.json
import utils.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0020_auto_20180327_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='stat',
            field=utils.model_fields.AttrJSONField(default=dict, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='file stats', verbose_name='stat'),
        ),
    ]
