# Generated by Django 2.0 on 2018-04-14 20:23

from django.db import migrations, models, connection


def set_filenames(apps, schema_editor):
    """Set filename and mime type fields."""
    function = """
    CREATE EXTENSION IF NOT EXISTS plpythonu;
    CREATE OR REPLACE FUNCTION mime_type(afilename text) RETURNS text AS
    $$
    suffix = afilename.split('.')[-1].lower()
    if suffix in ('jpg', 'jpeg'):
        return 'image/jpeg'
    if suffix == 'png':
        return 'image/png'
    if suffix == 'pdf':
        return 'application/pdf'
    else:
        return ''
    $$
    LANGUAGE 'plpythonu' VOLATILE;
    """
    update = """
    UPDATE photo_imagefile
    SET stem = substring(original, '^.*/(.*?)(\.[^.]+)?$'),
    stat = stat || jsonb_build_object('mimetype', mime_type(original)),
    full_width = coalesce(full_width, 0),
    full_height = coalesce(full_height, 0);
    """
    with connection.cursor() as cursor:
        cursor.execute(function)
        cursor.execute(update)


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0022_auto_20180412_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='stem',
            field=models.CharField(
                max_length=1024, null=True, verbose_name='filename stem'
            ),
        ),
        migrations.RunPython(
            code=set_filenames,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='stem',
            field=models.CharField(
                max_length=1024, verbose_name='filename stem'
            ),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='full_height',
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                help_text='full height in pixels',
                verbose_name='height'
            ),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='full_width',
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                help_text='full height in pixels',
                verbose_name='width'
            ),
        ),
    ]
