# Generated by Django 2.0 on 2018-05-03 19:47

import sorl.thumbnail.fields

import apps.photo.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0025_unique_together_story_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='original',
            field=sorl.thumbnail.fields.ImageField(
                height_field='full_height',
                max_length=1024,
                null=True,
                upload_to=apps.photo.models.upload_image_to,
                validators=[
                    django.core.validators.FileExtensionValidator([
                        'jpg', 'jpeg', 'png'
                    ])
                ],
                verbose_name='original',
                width_field='full_width'
            ),
        ),
    ]
