# Generated by Django 2.1 on 2018-08-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0026_auto_20180503_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='stem',
            field=models.CharField(
                blank=True, max_length=1024, verbose_name='file name stem'
            ),
        ),
    ]
