# Generated by Django 2.1 on 2018-08-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0027_auto_20180813_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='_imagehash',
            field=models.CharField(default='', editable=False, help_text='perceptual hash of image using ahash algorithm', max_length=16, verbose_name='image hash'),
        ),
    ]
