# Generated by Django 2.1.2 on 2018-11-17 01:41

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0030_auto_20181027_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='exif_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='exif_data', verbose_name='exif_data'),
        ),
    ]
