#!/bin/bash
# Bash script that starts gunicorn worker processes.
# Put in project bin/ folder and keep running with supervisor.

name="SITEURL"
virtualenvfolder="/srv/SITEURL/pyvenv/SITEURL"
socket="/tmp/SITEURL.socket"
user="USERNAME"
group="USERGROUP"
num_workers="3"
max_requests="0"
wsgi="core.wsgi"

source  $virtualenvfolder/bin/activate
# Activate the virtual environment.


# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)

exec    $virtualenvfolder/bin/gunicorn \
        $wsgi:application \
        --name $name \
        --workers $num_workers \
        --bind=unix:$socket \
        --user=$user --group=$group \
        --log-level=info \
        --max-requests=$max_requests
