#!/bin/bash
# Bash script that starts gunicorn worker processes.
# Put in project bin/ folder and keep running with supervisor.

virtualenvfolder="/srv/SITEURL/pyvenv/SITEURL"

source  $virtualenvfolder/bin/activate
# Activate the virtual environment.

case "$1" in

  celery-worker)
    exec $virtualenvfolder/bin/celery \
          worker -A core --loglevel=INFO
    ;;

  celery-beat)
    exec $virtualenvfolder/bin/celery \
          beat -A core --loglevel=INFO
    ;;

  gunicorn)
    name="SITEURL"
    socket="/tmp/SITEURL.socket"
    user="USERNAME"
    group="USERGROUP"
    num_workers="3"
    max_requests="0"
    wsgi="core.wsgi"
    exec    $virtualenvfolder/bin/gunicorn \
            $wsgi:application \
            --name $name \
            --workers $num_workers \
            --bind=unix:$socket \
            --user=$user --group=$group \
            --log-level=info \
            --max-requests=$max_requests
    ;;

  *)
    echo $"Usage: $0 {gunicorn|celery-worker|celery-beat}"
    exit 1
esac

